services:
  k8s-sims:
    image: thesmuks/k8s-sims:latest
    container_name: k8s-sims
    privileged: true
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./results:/results
      - ./modules:/modules
      - ./experiment-base.sh:/experiment-base.sh
    command: [
        "-e",
        "${EXPERIMENT_FILES_PATH}",
        "-n",
        "${RUNS}",
        "-s",
        "${START}",
        "-o",
        "${OUTPUT_FOLDER}",
        "-t",
        "${MEMORY_THRESHOLD}",
        "-x",
        "${MAX_SIMULATION_TIME}",
        # "-v",
      ]
