apiVersion: v1
kind: Pod
metadata:
  name: template_node_name
  namespace: kubemark
  labels:
    name: template_node_name
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/node
            operator: NotIn
            values:
            - "kubemark-node"
  containers:
  - name: init-inotify-limit
    image: busybox:1.32
    command: ['sysctl', '-w', 'fs.inotify.max_user_instances=1000']
    securityContext:
      privileged: true
  volumes:
  - name: kubeconfig-volume
    secret:
      secretName: kubeconfig
  - name: logs-volume
    hostPath:
      path: /var/log
  - name: containerd
    hostPath:
      path: /run/containerd
  - name: no-serviceaccount-access-to-real-master
    emptyDir: {}
  containers:
  - name: hollow-kubelet
    image: thesmuks/kubemark:v1.29.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4194
    - containerPort: 10250
    - containerPort: 10255
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    command: [
      "/kubemark",
      "--morph=kubelet",
      "--name=$(NODE_NAME)",
      "--kubeconfig=/kubeconfig/kubelet.kubeconfig",
      "--v=5",
      "--node-labels=node-role.kubernetes.io/node=kubemark-node",
      "--extended-resources=template_node_extended_resources"
    ]
    volumeMounts:
    - name: kubeconfig-volume
      mountPath: /kubeconfig
      readOnly: true
    - name: logs-volume
      mountPath: /var/log
    - name: containerd
      mountPath: /run/containerd
    resources:
      requests:
        cpu: 10m
        memory: 20M
    securityContext:
      privileged: true
  - name: hollow-proxy
    image: thesmuks/kubemark:v1.29.0
    imagePullPolicy: IfNotPresent
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    command: [
      "/kubemark",
      "--morph=proxy",
      "--name=$(NODE_NAME)",
      "--kubeconfig=/kubeconfig/kubeproxy.kubeconfig",
      "--v=5",
    ]
    volumeMounts:
    - name: kubeconfig-volume
      mountPath: /kubeconfig
      readOnly: true
    - name: logs-volume
      mountPath: /var/log
    resources:
      requests:
        cpu: 10m
        memory: 20M
    securityContext:
      privileged: true
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 900
