apiVersion: v1
clusters:
- cluster:
    server: http://192.168.1.216:3131
  name: kwok
contexts:
- context:
    cluster: kwok
  name: kwok
current-context: kwok
kind: Config
preferences: {}
users: null
